<?php

namespace AppBundle\Repository;

/**
 * PostGenreMappingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostGenreMappingRepository extends \Doctrine\ORM\EntityRepository
{
}
