<?php
 namespace AppBundle\Constants;
 
 class MailTemplates{
 	
 	public static function registerMail($options = array()){
 		
 		$template  = "<p> Hi ".$options['firstName']." ".$options['lastName']."</p>";
 		$template .= "<p> Welcome to the I do have Talent. Thank you for creating the acount. To verify your email, please click the below link </p>";
 		$template .= "<a href=".$options['url'].">".$options['url']."</a>";
 		$template .= "<p> Thank you </p> ";
 		$template .= "I do have Talent"; 
 		
 		return $template; 
 	}
 	
 	public static function resetPasswordMail($options = array()){
 	
 		$template  = "<p> Dear ".$options['firstName']." ".$options['lastName']."</p>";
 		$template .= "<p> This email has been generated by I do have Talent at your request. </p>";
 		$template .= "<p> Please use the following link to create a new password </p>";
 		$template .= "<a href=".$options['url'].">".$options['url']."</a>";
 		$template .= "<p> Thank you </p> ";
 		$template .= "I do have Talent";
 			
 		return $template;
 	}
 	
 }
 